# Generated by Django 4.0.1 on 2022-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_ride_arrivaltime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
