# Generated by Django 4.0.1 on 2022-01-27 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_ride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haha',
            old_name='phone_number_text',
            new_name='phone_number',
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30)),
                ('arrivaltime', models.DateTimeField(default=datetime.datetime(2022, 1, 27, 18, 26, 53, 100187, tzinfo=utc))),
                ('NumPassanger', models.IntegerField()),
                ('CanShare', models.IntegerField()),
                ('max_passanger', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('owner_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.haha')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_dirver', to='users.haha')),
                ('r_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_owner', to='users.haha')),
                ('r_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ride')),
                ('r_sharer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_sharer', to='users.haha')),
            ],
        ),
    ]
