# Generated by Django 4.0.1 on 2022-01-27 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_phone_number_text_haha_phone_number_ride_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 21, 1, 53, 118709, tzinfo=utc)),
        ),
    ]
