# Generated by Django 4.0.1 on 2022-01-27 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_haha_vehicle_id_alter_ride_arrivaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 22, 43, 16, 436304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
