# Generated by Django 4.0.1 on 2022-01-28 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_ride_arrivaltime_alter_ride_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='r_driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_dirver', to='users.haha'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='r_sharer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_sharer', to='users.haha'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 1, 7, 48, 380707, tzinfo=utc)),
        ),
    ]
