# Generated by Django 4.0.1 on 2022-01-28 01:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_relation_r_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='r_owner_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 1, 14, 11, 207644, tzinfo=utc)),
        ),
    ]
