# Generated by Django 4.0.1 on 2022-01-28 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_car_driver_id_alter_ride_arrivaltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='r_driver_id',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='r_owner_id',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='r_sharer_id',
        ),
        migrations.AddField(
            model_name='relation',
            name='r_driver_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='r_owner_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='r_sharer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 14, 16, 51, 548085, tzinfo=utc)),
        ),
    ]
