# Generated by Django 4.0.1 on 2022-01-28 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_relation_r_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 14, 34, 8, 341193, tzinfo=utc)),
        ),
    ]
